# Generated by Django 4.1.3 on 2022-11-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(model_name="post", old_name="content", new_name="body",),
        migrations.AlterField(
            model_name="post", name="expiration", field=models.DateTimeField(null=True),
        ),
    ]
