# Generated by Django 4.1.3 on 2022-11-26 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0002_rename_content_post_body_alter_post_expiration"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post", old_name="created_at", new_name="created_on",
        ),
        migrations.RenameField(
            model_name="post", old_name="modified_at", new_name="modified_on",
        ),
    ]
