# Generated by Django 4.1.3 on 2022-11-26 17:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("social", "0003_rename_created_at_post_created_on_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="dilikes",),
        migrations.AddField(
            model_name="post",
            name="dislikes",
            field=models.ManyToManyField(
                blank=True, related_name="dislikes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
