# Generated by Django 4.1.3 on 2022-11-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0004_remove_post_dilikes_post_dislikes"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="comments",
            field=models.ManyToManyField(
                blank=True, related_name="comments", to="social.comment"
            ),
        ),
    ]
