# Generated by Django 4.1.3 on 2022-11-27 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_post_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on', '-shared_on']},
        ),
    ]
