# Generated by Django 4.1.3 on 2022-11-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_replycomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.ManyToManyField(blank=True, related_name='replies', to='social.replycomment'),
        ),
    ]
