# Generated by Django 4.1.3 on 2022-12-07 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0008_comment_reply"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="image",),
        migrations.AddField(
            model_name="image",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="social.post",
            ),
        ),
    ]
