# Generated by Django 4.1.3 on 2022-12-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0010_remove_image_id_image_image_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="uploads/post_photos"
            ),
        ),
    ]
